package ast_expr;

//@formatter:off
public enum ExpressionBase {
   EASSIGN
 , EBINARY
 , EUNARY
 , EPRIMARY_IDENT
 , EPRIMARY_STRING
 , EPRIMARY_NUMBER
 , ECAST
 , EMETHOD_INVOCATION
 , EFIELD_ACCESS
 , ECLASS_INSTANCE_CREATION
 , ETHIS
 , ESTRING_CONST
 , ECHAR_CONST
 , EBOOLEAN_LITERAL
 , EBUILTIN_FN
}
