package njast.ast_kinds;

//@formatter:off
public enum ExpressionBase {
   EASSIGN
 , EBINARY
 , ECOMMA
 , ETERNARY
 , EUNARY
 , EPRIMARY_IDENT
 , EPRIMARY_STRING
 , EPRIMARY_NUMBER
 , ECAST
 , EMETHOD_INVOCATION
 , EPREINCDEC
 , EPOSTINCDEC
 , EFIELD_ACCESS
 , EGET_POINTER_TO_CLASS
 , ECLASS_INSTANCE_CREATION
}
